- 타이타닉 데이터셋 입력 컬럼(Feature) 상세 설명

| 컬럼명 | 설명 및 의미 | 비고 / 값 예시 |
| pclass | 객실 등급 (Ticket class) | 1 = 1등석, 2 = 2등석, 3 = 3등석 |
| sex | 성별 | male (남성), female (여성) |
| age | 나이 | 결측치 존재, 1세 미만은 소수점 표시 |
| sibsp | 동승한 형제/자매/배우자의 수 | 0, 1, 2 ... |
| parch | 동승한 부모/자녀의 수 | 0, 1, 2 ... |
| fare | 탑승 요금 | 승객이 지불한 운임 (파운드화) |
| embarked | 탑승 항구 코드 | C = Cherbourg, Q = Queenstown, S = Southampton |
| class | 객실 등급 텍스트 | First, Second, Third (pclass와 동일 정보) |
| who | 승객 구분 | man (성인 남성), woman (성인 여성), child (아이) |
| deck | 선실 구역 번호 | A, B, C, D, E, F, G (결측치 매우 많음) |
| embark_town | 탑승 도시 이름 | Cherbourg, Queenstown, Southampton |
| alone | 혼자 탑승했는지 여부 | True (동승자 없음), False (동승자 있음) |

In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
import platform
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression, LinearRegression, Lasso, Ridge
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix, ConfusionMatrixDisplay, mean_squared_error, root_mean_squared_error

# sklearn.set_config(display="text")

# 1. 운영체제별 한글 폰트 설정
if platform.system() == 'Windows':
    plt.rc('font', family='Malgun Gothic')
elif platform.system() == 'Darwin': # Mac OS
    plt.rc('font', family='AppleGothic')
else: # Linux (Colab 등)
    plt.rc('font', family='NanumBarunGothic')

 
# 2. 마이너스 기호(-) 깨짐 방지
plt.rcParams['axes.unicode_minus'] = False

In [2]:
[문제 0] 프로젝트 목표 정의 

1. 데이터 수집·전처리부터 모델 학습, 성능 평가까지 이어지는 머신러닝 파이프라인의 전체 구조를 명확히 제시하세요.
2. 학습(Train) 및 평가(Test) 과정에서 발생할 수 있는 데이터 누수(Data Leakage)를 방지하기 위한 데이터 분리 및 처리 전략을 포함하여 기술하세요.

In [29]:
"""
    타이타닉 승객 정보를 통해 승객의 생존여부를 예측한다
    결측치와 필요없은 데이터를 제거하는 전처리 과정을 거치고 
    범주형 변수는 인-핫 인코딩을 적용하고 표준화를 한다
    학습데이터와 테스트 데이터를 8:2로 분리시킨다
    모댈 학습시키고 생존여부 예측하고 모델 성능 평가를 한다 
"""

'\n    타이타닉 승객 정보를 통해 승객의 생존여부를 예측한다\n    결측치와 필요없은 데이터를 제거하는 전처리 과정을 거치고 \n    범주형 변수는 인-핫 인코딩을 적용하고 표준화를 한다\n    학습데이터와 테스트 데이터를 8:2로 분리시킨다\n    모댈 학습시키고 생존여부 예측하고 모델 성능 평가를 한다 \n'

In [4]:
# [문제 1] 데이터 확인 및 EDA 

# 1-1. 데이터의 행/열 개수, 컬럼명, 결측치 개수(컬럼별) 요약을 작성하고, 이상치를 탐색를 각 컬럼의 이상치로 판단하거나 이상치로 보지 않은 근거를 서술하세요
# 1-2. Survived 클래스 비율(생존/사망 비율)을 계산하고 해석하세요.

In [5]:
[문제 2] 다음 조건을 만족하도록 전처리를 설계하세요. (20점)

1. 수치형/범주형 변수를 구분하라. (5점)
2. 결측치 처리 전략을 각각 제시하세요. (예: age, embarked 등) (5점)
3. 범주형 인코딩 방법(원-핫 등)과 수치형 스케일링 필요 여부를 판단하고 근거를 서술하세요. (5점)
4. 스케일링을 표준화로 할지 정규화로 할지 판단 근거를 서술하세요.

In [6]:
[문제 3] 데이터 분리 및 검증 전략 

1. 학습/테스트 데이터를 분리하세요. 
2. 분리 시 stratify(계층화) 적용 여부를 결정하고 이유를 설명하세요.

In [7]:


base_path = r"/Users/kdt_0900_lyn/data_analysis/resource/dataset"
file_name = r"titanic.csv"
file_path = os.path.join(base_path, file_name) 

df = pd.read_csv(file_path)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [8]:
수치형 : PassengerId, Age, SibSp, Parch, Fare
분류형: Survived, Pclass, Name, Sex, Ticket, Cabin, Embarked
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [9]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [10]:
"""
    "Cabin", "Name", "Ticket", "PassengerId" 이 데이터는 생존과 연관이 없으므로 제거한다 
    "Age" 이 데이터는 NaN값아 았으므로 중앙값으로 대체한다 
    
"""

'\n    "Cabin", "Name", "Ticket", "PassengerId" 이 데이터는 생존과 연관이 없으므로 제거한다 \n    "Age" 이 데이터는 NaN값아 았으므로 중앙값으로 대체한다 \n\n'

In [11]:

df = pd.get_dummies(df, columns=["Sex", "Embarked"], drop_first=True, dtype= int)

In [12]:
df["Age"] = df["Age"].fillna(df["Age"].median())
df

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Sex_male,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,1,0,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,0,0,0
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,0,0,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,0,0,1
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",27.0,0,0,211536,13.0000,NaN,1,0,1
887,888,1,1,"Graham, Miss. Margaret Edith",19.0,0,0,112053,30.0000,B42,0,0,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",28.0,1,2,W./C. 6607,23.4500,NaN,0,0,1
889,890,1,1,"Behr, Mr. Karl Howell",26.0,0,0,111369,30.0000,C148,1,0,0
890,891,0,3,"Dooley, Mr. Patrick",32.0,0,0,370376,7.7500,NaN,1,1,0

In [13]:
df = df.drop(["Cabin", "Name", "Ticket", "PassengerId"], axis=1)
df.head()

,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_male,Embarked_Q,Embarked_S
0,0,3,22.0,1,0,7.2500,1,0,1
1,1,1,38.0,1,0,71.2833,0,0,0
2,1,3,26.0,0,0,7.9250,0,0,1
3,1,1,35.0,1,0,53.1000,0,0,1
4,0,3,35.0,0,0,8.0500,1,0,1

In [28]:
print(df["Survived"].value_counts())
print(df["Survived"].value_counts(normalize=True)*100)
"""
    0(사망) : 549명 61%
    1(생존) : 342명 38%
    생존자와 사망자의 수차는 이렇게 나온다 
"""

Survived
0    549
1    342
Name: count, dtype: int64
Survived
0    61.616162
1    38.383838
Name: proportion, dtype: float64

In [14]:

X = df.drop(["Survived"], axis=1)
X.head()

   Pclass   Age  SibSp  Parch     Fare  Sex_male  Embarked_Q  Embarked_S
0       3  22.0      1      0   7.2500         1           0           1
1       1  38.0      1      0  71.2833         0           0           0
2       3  26.0      0      0   7.9250         0           0           1
3       1  35.0      1      0  53.1000         0           0           1
4       3  35.0      0      0   8.0500         1           0           1

In [15]:
y = df["Survived"]
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [16]:
# X = df.drop(["Cabin", "Name"], axis=1)
# print(X.head())
# """
#     "Name", "Cabin"은 분석하기 적합하지 않음 
# """

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2026, stratify=y)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)
"""
stratify(계층화) 적용 하는 이유 : 계층화를 적용하면 학습 데이터와 테스트 데이터 모두에서 사망/생존 
비율이 원본 데이터와 비슷하게 유지되기 떄문
"""

(712, 8) (179, 8) (712,) (179,)

'\nstratify(계층화) 적용 하는 이유 : 계층화를 적용하면 학습 데이터와 테스트 데이터 모두에서 사망/생존 \n비율이 원본 데이터와 비슷하게 유지되기 떄문\n'

In [18]:
print(df.shape)
print(df)
print(df.isnull().sum())
print(df.describe())

(891, 9)
     Survived  Pclass   Age  SibSp  Parch     Fare  Sex_male  Embarked_Q  \
0           0       3  22.0      1      0   7.2500         1           0
1           1       1  38.0      1      0  71.2833         0           0
2           1       3  26.0      0      0   7.9250         0           0
3           1       1  35.0      1      0  53.1000         0           0
4           0       3  35.0      0      0   8.0500         1           0
..        ...     ...   ...    ...    ...      ...       ...         ...
886         0       2  27.0      0      0  13.0000         1           0
887         1       1  19.0      0      0  30.0000         0           0
888         0       3  28.0      1      2  23.4500         0           0
889         1       1  26.0      0      0  30.0000         1           0
890         0       3  32.0      0      0   7.7500         1           1

     Embarked_S
0             1
1             0
2             1
3             1
4             1
..          ...
886           1
887           1
888           1
889           0
890           0

[891 rows x 9 columns]
Survived      0
Pclass        0
Age           0
SibSp         0
Parch         0
Fare          0
Sex_male      0
Embarked_Q    0
Embarked_S    0
dtype: int64
         Survived      Pclass         Age       SibSp       Parch        Fare  \
count  891.000000  891.000000  891.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.361582    0.523008    0.381594   32.204208
std      0.486592    0.836071   13.019697    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   22.000000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   35.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

         Sex_male  Embarked_Q  Embarked_S
count  891.000000  891.000000  891.000000
mean     0.647587    0.086420    0.722783
std      0.477990    0.281141    0.447876
min      0.000000    0.000000    0.000000
25%      0.000000    0.000000    0.000000
50%      1.000000    0.000000    1.000000
75%      1.000000    0.000000    1.000000
max      1.000000    1.000000    1.000000

In [19]:
print(df["Survived"].value_counts())

Survived
0    549
1    342
Name: count, dtype: int64

In [20]:
[문제 4] 모델 학습 

1. 기본 모델 1개 이상: (예: Logistic Regression, Lasso, Ridge, RandomForest 등) 
2. 모델 학습 및 예측까지 이어지는 전체 흐름과 각 단계별 핵심 코드를 작성하세요. 
3. 파라미터와 하이퍼파라미터의 차이를 서술하고, 하이퍼파라미터 튜닝을 “최소 1개 파라미터”만이라도 시도하세요.

In [21]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
lr = LinearRegression()
lr.fit(X_train_scaled, y_train)
y_pred = lr.predict(X_test_scaled)
print(y_pred)

[ 0.10991392 -0.02579955  1.02942197  0.12749824  0.09812213  0.02735103
  1.00083181  0.6605961   0.28351401  0.64579668  0.14268146  0.13364718
  0.14497793  0.50153734  0.1687865   0.29203783  0.06865252  0.96662855
  0.90892884  0.10761422 -0.03095698  0.19220396  0.31830429  0.09227805
  0.13356451  0.49082422  0.10408455  0.36531028  0.18039619  0.0923244
  0.50543685  0.85299358  0.22859338  0.05758456  0.4533783  -0.03754719
 -0.00144071  0.29429002  0.16316345  0.7977045   0.96839381  0.28688611
  1.03627135  0.13381871  0.5482173   0.16830552  0.06272546  0.58167537
  0.73135607  0.2584069   0.92533191  0.57678313  0.6258818   0.07286687
  0.94970681  0.09227805  0.0923244   0.89672436  0.09227805  0.03014578
  0.14545369  0.18621018  0.68423261  0.15698213  0.05690487  0.62660906
  0.09227805  0.30812289  0.45649783  0.0604631   0.74112064  0.14609123
  0.89197292  0.16857358  0.12863445  0.37540555  0.82452946  0.66068003
  0.05690487  0.80219512  0.13990366  0.14497793  0.06866503  0.20798112
  0.25736984  0.73671126  0.18039746  0.09421188  0.80055902  0.14517832
  0.87009039  0.74540546  0.78373383  0.2791104   0.20814853  0.61774542
  0.11959971  0.78410852  0.3223359   0.11589106  0.36011781  0.01338233
  0.74316258  0.52250166  0.23593108  0.45130406  0.64795898  0.48114959
  0.73984867  0.67797933  0.14542383 -0.21804752  0.85472607  0.09653316
  0.44861357  0.06276177  0.60759584  0.34410236  0.98554794  0.45479118
  0.03491221  0.87435093  0.09088985  0.70856974  0.37778726  0.73135607
  0.43201253  0.42623486  0.19072401  0.07588052  0.74980564  0.32536315
  0.9181596   0.88279874  0.54095417  0.14158699  0.44861357  0.61240516
  0.15744432  0.09208391  0.0923244   0.13949157  0.64322446  0.32775797
  0.1138051   0.45626419  0.45115376  0.7656355   0.16854428  0.65438243
  0.12758484  0.67797933  0.12178181  0.10979367  0.37569648  0.85587017
  0.00986297  0.69916493  0.13357076  0.27649224  1.02312461  0.20058017
  0.66238306 -0.00323771  0.13998632  0.15127427  0.6627599   0.41261908
  0.10973355  0.65095339  0.08636854  1.07511538  0.79957073  0.25589544
  0.16857358 -0.21804752  0.06137358  0.67797933  0.11298579]

In [22]:
[문제 5] 평가 및 리포트

1. Accuracy, Precision, Recall, F1 중 최소 2개 이상 사용하여 모델을 평가하세요.
2. Confusion Matrix 해석하세요. 
3. 어떤 오류가 더 치명적인지(예: 생존자를 사망으로 예측 vs 반대) 상황을 가정해 서술하세요.

In [23]:
lr = LogisticRegression()
lr.fit(X_train_scaled, y_train)
y_pred = lr.predict(X_test_scaled)

y_prob = lr.predict_proba(X_test_scaled)[:, 1]
y_prob_percent = y_prob * 100

for i, proba in enumerate(y_prob_percent[:20], 1):
    print(f"샘플 {i}번의 합격 확률 : {proba:.2f}%")

샘플 1번의 합격 확률 : 10.05%
샘플 2번의 합격 확률 : 4.31%
샘플 3번의 합격 확률 : 95.93%
샘플 4번의 합격 확률 : 10.67%
샘플 5번의 합격 확률 : 9.55%
샘플 6번의 합격 확률 : 6.04%
샘플 7번의 합격 확률 : 95.23%
샘플 8번의 합격 확률 : 68.96%
샘플 9번의 합격 확률 : 25.15%
샘플 10번의 합격 확률 : 66.28%
샘플 11번의 합격 확률 : 11.16%
샘플 12번의 합격 확률 : 11.58%
샘플 13번의 합격 확률 : 12.14%
샘플 14번의 합격 확률 : 57.95%
샘플 15번의 합격 확률 : 13.72%
샘플 16번의 합격 확률 : 26.41%
샘플 17번의 합격 확률 : 7.82%
샘플 18번의 합격 확률 : 93.87%
샘플 19번의 합격 확률 : 91.53%
샘플 20번의 합격 확률 : 9.91%

In [24]:
acc = accuracy_score(y_test, y_pred)
print(f"로지스틱 회귀 정확도 : {acc}")

로지스틱 회귀 정확도 : 0.776536312849162

In [25]:
coef_df = pd.DataFrame({
    "Accuracy": X_train.columns,   
    "Precision": lr.coef_[0]
}).sort_values(by="Precision", ascending=False)
coef_df

     Accuracy  Precision
4        Fare   0.110118
6  Embarked_Q   0.039165
3       Parch  -0.080505
7  Embarked_S  -0.147725
2       SibSp  -0.249867
1         Age  -0.509902
0      Pclass  -0.938555
5    Sex_male  -1.302016

In [26]:
"""
    Confusion Matrix는 모델이 생존자와 사망자를 얼마나 정확하게 구분했는지 보여주는 표이다
    실제 사망자를 사망으로 예측하거나 실제 생존자를 생존으로 예측하는 경우는 맞게 예측한거이다
"""
"""
    구조상황일경우 실제 생존자를 사망으로 예측하는 오류가 발생하는 경우가 더 치명적이다
    이유는 구조할 수 있는 사람을 구조하지 못할 수도 있기 떄문이다
"""

'\n    구조상황일경우 실제 생존자를 사망으로 예측하는 오류가 발생하는 경우가 더 치명적이다\n    이유는 구조할 수 있는 사람을 구조하지 못할 수도 있기 떄문이다\n'

In [27]:
[문제 6] 최종 제출물 구성

1. 데이터 요약(EDA 결과 핵심 3가지)하여 서술하세요. 
2. 전처리 전략 요약(결측/인코딩/스케일링)하여 서술하세요.
3. 모델 선택 이유와 학습 설정(튜닝 포함)을 요약하여 서술하세요.
4. 최종 성능 지표 및 해석과 개선 아이디어 1개 이상 서술하세요.

In [ ]:
"""
    1. EDA 결과 핵심 
    (1) 생존비율 : 사망자 549명 (61%), 생존자 342명(38%)로  사망자가 더 많음 
    (2) 결측치 확인 후 제거 혹은 대체
    (3) 분류형을 수치형으로 변환 
    
    2. 전처리 전략 요약(결측/인코딩/스케일링) 
    : 결측치는 중앙값으로 대체 필요없는 데이터는제거,
    인-핫 인코딩은 분류형을 수치형으로 변환가능,
    수치형 변수는 표준화가능 
    
    3. 모델 선택 이유와 학습 설정
    : 0과 1로 이루어진 이진분류 모델이기 때문 ,
     테스트 데이터를 학습하지 않기 위해 20%만 테스트용으로 사용

"""